"""initial schema

Revision ID: 4f9b09f1b9cb
Revises: 
Create Date: 2026-09-03 16:38:48.919799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f9b09f1b9cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('makineler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('makine_kodu', sa.String(length=50), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('tip', sa.String(length=10), nullable=False),
    sa.Column('kritiklik', sa.Integer(), nullable=False),
    sa.CheckConstraint('kritiklik BETWEEN 1 AND 5', name='ck_makine_kritiklik_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_makineler_makine_kodu'), 'makineler', ['makine_kodu'], unique=True)
    op.create_table('stok',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parca_kodu', sa.String(length=50), nullable=False),
    sa.Column('ad', sa.String(length=100), nullable=False),
    sa.Column('adet', sa.Integer(), nullable=False),
    sa.Column('tedarik_gun', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stok_parca_kodu'), 'stok', ['parca_kodu'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ariza_parca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ariza_tipi', sa.Enum('TWF', 'HDF', 'PWF', 'OSF', name='failuretype'), nullable=False),
    sa.Column('parca_kodu', sa.String(length=50), nullable=False),
    sa.Column('onerilen_aksiyon', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['parca_kodu'], ['stok.parca_kodu'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ariza_parca_ariza_tipi'), 'ariza_parca', ['ariza_tipi'], unique=False)
    op.create_table('tahminler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('makine_id', sa.Integer(), nullable=False),
    sa.Column('risk_orani', sa.Float(), nullable=False),
    sa.Column('ariza_tipi', sa.Enum('TWF', 'HDF', 'PWF', 'OSF', name='failuretype'), nullable=False),
    sa.Column('gerekce', sa.JSON(), nullable=False),
    sa.Column('oncelik', sa.Integer(), nullable=False),
    sa.Column('durum', sa.Enum('bekliyor', 'onaylandi', 'reddedildi', name='tahmindurum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('oncelik BETWEEN 1 AND 5', name='ck_tahmin_oncelik_range'),
    sa.ForeignKeyConstraint(['makine_id'], ['makineler.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tahminler_makine_id'), 'tahminler', ['makine_id'], unique=False)
    op.create_table('is_emirleri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tahmin_id', sa.Integer(), nullable=False),
    sa.Column('makine_id', sa.Integer(), nullable=False),
    sa.Column('aksiyon', sa.String(length=255), nullable=False),
    sa.Column('parca_kodu', sa.String(length=50), nullable=False),
    sa.Column('oncelik', sa.Integer(), nullable=False),
    sa.Column('durum', sa.Enum('bekliyor', 'tamamlandi', 'iptal', name='isemridurum'), nullable=False),
    sa.Column('onaylayan_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('oncelik BETWEEN 1 AND 5', name='ck_is_emri_oncelik_range'),
    sa.ForeignKeyConstraint(['makine_id'], ['makineler.id'], ),
    sa.ForeignKeyConstraint(['onaylayan_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parca_kodu'], ['stok.parca_kodu'], ),
    sa.ForeignKeyConstraint(['tahmin_id'], ['tahminler.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tahmin_id')
    )
    op.create_index(op.f('ix_is_emirleri_makine_id'), 'is_emirleri', ['makine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_is_emirleri_makine_id'), table_name='is_emirleri')
    op.drop_table('is_emirleri')
    op.drop_index(op.f('ix_tahminler_makine_id'), table_name='tahminler')
    op.drop_table('tahminler')
    op.drop_index(op.f('ix_ariza_parca_ariza_tipi'), table_name='ariza_parca')
    op.drop_table('ariza_parca')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stok_parca_kodu'), table_name='stok')
    op.drop_table('stok')
    op.drop_index(op.f('ix_makineler_makine_kodu'), table_name='makineler')
    op.drop_table('makineler')
    # ### end Alembic commands ###
