"""add karar tracking to tahminler

Revision ID: bf20935da7ca
Revises: 4f9b09f1b9cb
Create Date: 2026-09-07 19:32:29.531489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf20935da7ca'
down_revision: Union[str, Sequence[str], None] = '4f9b09f1b9cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tahminler', sa.Column('karar_veren_user_id', sa.Integer(), nullable=True))
    op.add_column('tahminler', sa.Column('karar_tarihi', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'tahminler', 'users', ['karar_veren_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tahminler', type_='foreignkey')
    op.drop_column('tahminler', 'karar_tarihi')
    op.drop_column('tahminler', 'karar_veren_user_id')
    # ### end Alembic commands ###
